name: NodeJS with Gulp

on:
  push:
    branches: [ ELN_Extractor_Simplify ]
  pull_request:
    branches: [ ELN_Extractor_Simplify ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm install
        gulp pack-linux
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-yml
        path: |
          dist
          !dist/*ml
